server:
  port: 8080

spring:
  application:
    name: ${springboot.app.name:diploma}
  cloud:
    service-registry:
      auto-registration:
        fail-fast: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://${registry.host:localhost}:${registry.port:8761}/eureka
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1
    prefer-ip-address: true
